---
editor: 
  markdown: 
    wrap: 72
---
 
```{r}
library(sf)
library(tmap)
library(tidyverse)
library(here)
library(knitr)
library(mapview)
library(units)
```
 
 
```{r}

source(knitr::purl(here("R",'src', "law_simulator.qmd")))
source(knitr::purl(here("R",'src', "boundary_registry_data.qmd")))
```
 
 
```{r}

undeveloped_region <- st_read('/capstone/pyforest/data/undeveloped/undeveloped.gpkg')

st_crs(undeveloped_region) <- "+proj=utm +zone=21 +south +ellps=WGS84 +datum=WGS84 +units=m +no_defs"


#dist_filadelphia <- st_read('/capstone/pyforest/data/dist_filadelphia/dist_filadelphia.shp')

#roads <- st_read(here('/capstone/pyforest/data/roads_hydrology/ly_via2.shp'))  
#st_crs(hydro) <- "+proj=utm +zone=21 +south +ellps=WGS84 +datum=WGS84 +units=m +no_defs"

#dept <- st_read(here('/capstone/pyforest/data/Political_Boundaries/departamento.shp')) |>
#  filter(dpto %in% c('P','Q', 'R')) 

#study_boundary <- st_union(dept, is_coverage = TRUE)

#st_write(study_boundary, '/capstone/pyforest/data/study_boundary/study_boundary.shp')

#road <- st_read(here('/capstone/pyforest/data/dissolved_road/dissolved_road.gpkg'))


st_erase = function(x, y) st_difference(x, st_union(st_combine(y)))
```


```{r}
#roads_buffer <- st_buffer(roads, dist = 50, nQuadSegs = 60)
#plot(roads_buffer)

#study_roads <- st_difference(study_boundary, roads)
```

```{r}

#undeveloped <- st_erase(undeveloped_region, road)

#st_write(undeveloped, '/capstone/pyforest/data/undeveloped.gpkg')
tmap_mode('view')
tmap_options(check.and.fix = TRUE)
tm_shape(undeveloped_region) +
  tm_fill(col = 'red') 

```
 
 


```{r}
st_crs(active_inactive) <- "+proj=utm +zone=21 +south +ellps=WGS84 +datum=WGS84 +units=m +no_defs"

```


```{r}

property_size <- active_inactive |>
  mutate(property_area = st_area(active_inactive), .before = geometry) |>
  drop_units() |>
  st_drop_geometry() 

avg_property <- property_size |>
  summarize(mean = mean(property_area)) |> 
  as.integer()

#ggplot(property_size, aes(x = anho_capa, y = property_area)) +
#  geom_col()

ggplot(property_size, aes(x = property_area)) +
  geom_histogram()

```
 
 
```{r}
dimensions <- property_dimensions(desired_area = 40000000) 
```
 
```{r}

#property_boundary  <- study_boundary
undeveloped_gridded <- grid_rotate(boundary_property = undeveloped_region, x_y = dimensions) |> st_as_sf()




plot(undeveloped_gridded)
tmap_mode('view') 
tmap_options(check.and.fix = TRUE)
tm_shape(undeveloped_gridded) +
  tm_sf()

average_properties <- undeveloped_gridded |> 
  mutate(cat = seq(1:7338), 
         area = st_area(undeveloped_gridded), .before = x) |>
  drop_units() |>
  filter(area > 10000000) |>
  rename(geometry = x)

st_write(average_properties,
        '/capstone/pyforest/data/undeveloped/average_properties.shp')
#st_crs(average_properties) <- "+proj=utm +zone=21 +south +ellps=WGS84 +datum=WGS84 +units=m +no_defs"

plot(average_properties['area'])
hist(average_properties$area)
tmap_mode('plot')
tm_shape(average_properties) +
  tm_sf(col = 'area')
```
 
 

 

 
 
```{r}
tm_shape(limit_lu) +
  tm_borders(col = 'red')
```
 
 
```{r}
# system.time({
#   source(knitr::purl(here("R",'src', "forest_cover_vars.qmd")))
# }) 

#districts <- st_read('/capstone/pyforest/data/Political_Boundaries/distritos.shp') |>
#  st_make_valid()

#departments <- st_read('/capstone/pyforest/data/Political_Boundaries/departamento.shp') |>
#  st_make_valid()

#wildlife_protected <- st_read('/capstone/pyforest/data/Wildlife_Protection_Areas/ASP_ROCC.shp')

#certificadas <- st_read('/capstone/pyforest/data/Certificadas/certificadas.shp')

#indigenous_land <- st_read('/capstone/pyforest/data/Indigenous_Land/native_land.shp')

```
 


```{r}
#https://gis.stackexchange.com/questions/375345/dividing-polygon-into-parts-which-have-equal-area-using-r



# library(mapview)
# library(dismo)
# library(osmdata)  
# library(mapview)
# split_poly <- function(sf_poly, n_areas){
# # create random points
# points_rnd <- st_sample(sf_poly, size = 10000)
# #k-means clustering
# points <- do.call(rbind, st_geometry(points_rnd)) %>%
#   as_tibble() %>% setNames(c("lon","lat"))
# k_means <- kmeans(points, centers = n_areas)
# # create voronoi polygons
# voronoi_polys <- dismo::voronoi(k_means$centers, ext = sf_poly)
# # clip to sf_poly
# crs(voronoi_polys) <- crs(sf_poly)
# voronoi_sf <- st_as_sf(voronoi_polys)
# equal_areas <- st_intersection(voronoi_sf, sf_poly)
# equal_areas$area <- st_area(equal_areas)
# return(equal_areas)
# }
```

```{r}
# This is a script that approximates the fractions, it has a great field for optimization. It only does horizontal cutting, not in an oriented bounding box. In the porcientos argument you may put as many values as you like, it is not only for halves (c(.5,.5), this means c(.4, .3, .2, .1) would be a valid vector as well.

# library(units)
# library(sf)
# library(dplyr)
# library(osmdata)
# 
# pol <- osmdata::getbb("aguascalientes", format_out = "sf_polygon") 
# porcientos <- c(.5,.5) # the half argument
# 
# polycent <- function(poly, porcientos) {
#   df   <- st_sf(id = 1:length(porcientos), crs = 4326, # empty sf for populating
#                 geometry = st_sfc(lapply(1:length(porcientos), function(x) st_multipolygon())))
#   area1 <- st_area(poly) %>% sum() # st_area takes multipolygons as one; # area1 is constant
#   poly2 <- poly # duplicating for the final cut
#   for(j in  seq_along(porcientos[-length(porcientos)])) { 
#     bb = st_bbox(poly2)
#     top <- bb['ymax']
#     bot <- bb['ymin']
#     steps <- seq(bot, top, by = (top - bot) / 80)
#     for(i in steps[2:length(steps)]) {  # 2:n because 1:n renders a line "ymax" = "ymin"
#       bf <- bb
#       bf['ymax'] = i
#       temp <- st_intersection(poly, st_as_sfc(bf, 4326))
#       area2 <- st_area(temp) %>% sum()           # con get(.., i) coz st_area prints rounded
#       if(drop_units(area2)/drop_units(area1) >= porcientos[j]) break
#       df$geometry[j] <- st_geometry(temp)
#     }
#     poly2 <- st_difference(poly2, st_union(df))
#   }
#   df$geometry[length(porcientos)] <- st_geometry(st_difference(poly, st_union(df)))
#   poly <- df
# }
```

# Test for undeveloped region polygons with st_make_grid

```{r}

# Create a dataset of sfc cells using st_make_grid
#bbox <- st_bbox(c(0, 0, 10, 10))
#grid_size <- c(2, 2)
#grid <- st_make_grid(bbox, cellsize = c(diff(bbox[c(1, 3)]) / grid_size[1],
#                                         diff(bbox[c(2, 4)]) / grid_size[2]))

```

# Source Functions



Variables to call with: property_select(): property_cat

property_dimension(): paddock_area = 999000, hedgerow_width = 50,
width_paddock = 1, height_paddock = 1, tol = 0.01, new_dim = NULL,
max_iter = 100

